return {
    -- 'https://gitlab.com/gitlab-org/editor-extensions/gitlab.vim.git',
    --
    -- -- Activate when a file is created/opened
    -- event = { 'BufReadPre', 'BufNewFile' },
    --
    -- -- Activate when a supported filetype is open
    -- ft = {
    --     'python',
    --     'c',
    --     'cpp',
    --     'java',
    --     'go',
    --     'javascript',
    --     'sql',
    --     'sh',
    --     'css',
    --     'html',
    --     'terraform',
    --     'markdown'
    -- },
    --
    -- cond = function()
    --     -- Only activate if token is present in environment variable.
    --     -- Remove this line to use the interactive workflow.
    --     return vim.env.GITLAB_TOKEN ~= nil and vim.env.GITLAB_TOKEN ~= ''
    -- end,
    --
    -- opts = {
    --     statusline = {
    --         -- Hook into the built-in statusline to indicate the status
    --         -- of the GitLab Duo Code Suggestions integration
    --         enabled = true,
    --     },
    --},


    -- 'https://gitlab.com/gitlab-org/editor-extensions/gitlab.vim.git',
    --
    -- config = function()
    --     require('gitlab').setup({
    --         statusline = { enabled = false },
    --         code_suggestions = {
    --             auto_filetypes = { 'python' },
    --             ghost_text = {
    --                 enabled = true,
    --                 toggle_enabled = "<C-s>",
    --                 -- accept_suggestion = "<C-l>
    --                 -- clear_suggestions = "<C-l>
    --                 stream = true,
    --             }
    --         }
    --     })
    -- end
}
